<?xml version="1.0" encoding="UTF-8"?>
<definitions name="podatNavrh" targetNamespace="http://j2ee.netbeans.org/wsdl/PostiovnaSchema/schema/podatNavrh"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/PostiovnaSchema/schema/podatNavrh" xmlns:ns="http://xml.netbeans.org/schema/poistovna" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/PostiovnaSchema/schema/podatNavrh">
            <xsd:import namespace="http://xml.netbeans.org/schema/poistovna" schemaLocation="poistovna.xsd"/>
        </xsd:schema>
    </types>
    <message name="podatNavrhRequest">
        <part name="navrh" element="ns:podatNavrh"/>
    </message>
    <message name="podatNavrhResponse">
        <part name="part1" element="ns:podatNavrhRes"/>
    </message>
    <portType name="podatNavrhPortType">
        <operation name="podatNavrh">
            <input name="input1" message="tns:podatNavrhRequest"/>
            <output name="output1" message="tns:podatNavrhResponse"/>
        </operation>
    </portType>
    <binding name="podatNavrhBinding" type="tns:podatNavrhPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="podatNavrh">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="podatNavrhService">
        <port name="podatNavrhPort" binding="tns:podatNavrhBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/podatNavrhService/podatNavrhPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="podatNavrh">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="podatNavrhPortTypeRole" portType="tns:podatNavrhPortType"/>
    </plnk:partnerLinkType>
</definitions>
