<?xml version='1.0' encoding='UTF-8'?><!-- Published by JAX-WS RI (http://jax-ws.java.net). RI's version is Metro/2.3.2-b608 (trunk-7979; 2015-01-21T12:50:19+0000) JAXWS-RI/2.2.11-b150120.1832 JAXWS-API/2.2.12 JAXB-RI/2.2.12-b141219.1637 JAXB-API/2.2.13-b141020.1521 svn-revision#unknown. --><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/PostiovnaSchema/schema/podatNavrh" xmlns:ns="http://xml.netbeans.org/schema/poistovna" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="podatNavrh" targetNamespace="http://j2ee.netbeans.org/wsdl/PostiovnaSchema/schema/podatNavrh">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/PostiovnaSchema/schema/podatNavrh">
            <xsd:import namespace="http://xml.netbeans.org/schema/poistovna" schemaLocation="http://localhost:8080/PoistovnaService/podatNavrhService?xsd=1"/>
        </xsd:schema>
    </types>
    <message name="podatNavrhRequest">
        <part name="navrh" element="ns:podatNavrh"/>
    </message>
    <message name="podatNavrhResponse">
        <part name="part1" element="ns:podatNavrhRes"/>
    </message>
    <portType name="podatNavrhPortType">
        <operation name="podatNavrh">
            <input name="input1" message="tns:podatNavrhRequest"/>
            <output name="output1" message="tns:podatNavrhResponse"/>
        </operation>
    </portType>
    <binding name="podatNavrhBinding" type="tns:podatNavrhPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="podatNavrh">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="podatNavrhService">
        <port name="podatNavrhPort" binding="tns:podatNavrhBinding">
            <soap:address location="http://localhost:8080/PoistovnaService/podatNavrhService"/>
        </port>
    </service>
    <plnk:partnerLinkType name="podatNavrh">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="podatNavrhPortTypeRole" portType="tns:podatNavrhPortType"/>
    </plnk:partnerLinkType>
</definitions>